[package]
name = "connect-4"
version = "1.0.0"
edition = "2021"
default-run = "connect-4"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
slint = "1.4"

[build-dependencies]
slint-build = "1.4"
