import { Button, VerticalBox, HorizontalBox, GroupBox } from "std-widgets.slint";


struct pieceData {
    player_piece: int,
}

component piece inherits Rectangle {
    callback clicked;
    in property <int> player_piece: 0; // 0 (no player), 1 (player 1), 2 (player 2)

    width: 50px;
    height: 50px;
    background: player_piece == 1 ? #ff0000 : player_piece == 2 ? #0000ff : #ffffff;
    animate background { duration: 5000ms; }

    TouchArea {
        clicked => {
            // Delegate to the user of this element
            root.clicked();
        }
    }
}


export component AppWindow inherits Window {
    in-out property <int> player: 0;
    in-out property <int> player_type: 0;
    in-out property <int> player_1_type: 0;
    in-out property <int> player_2_type: 0;

    in property <[pieceData]> pieces: [
        { player_piece: 0 },
    ];

    callback set_player_type();
    callback request_run_game();

    default-font-size: 15px;
    VerticalBox {
        Text {
            text: 
                "player: 1, player type: \{root.player_1_type} \n" + 
                "player: 2, player type: \{root.player_2_type} \n\n" +
                "Select player \{root.player+1} type:";
        }
        HorizontalBox {
            Button {
                text: "Random";
                clicked => {
                    root.player_type = 0;
                    root.player = Math.mod(root.player + 1, 2);
                    root.set_player_type();
                }
            }
            Button {
                text: "Human";
                clicked => {
                    root.player_type = 1;
                    root.player = Math.mod(root.player + 1, 2);
                    root.set_player_type();
                }
            }
            Button {
                text: "Bot";
                clicked => {
                    root.player_type = 2;
                    root.player = Math.mod(root.player + 1, 2);
                    root.set_player_type();
                }
            }
            Button {
                text: "Bit Bot";
                clicked => {
                    root.player_type = 3;
                    root.player = Math.mod(root.player + 1, 2);
                    root.set_player_type();
                }
            }
            Button {
                text: "Bit Bot 2";
                clicked => {
                    root.player_type = 4;
                    root.player = Math.mod(root.player + 1, 2);
                    root.set_player_type();
                }
            }
        }
        // make a 6x7 grid of pieces
        Rectangle {
            x: 0px;
            width: 420px;
            height: 360px;
            for p[i] in pieces : piece {
                x: Math.mod(i, 7) * 60px;
                y: Math.floor(i / 7) * 60px;
                width: 50px;
                height: 50px;
                player_piece: p.player_piece;
                clicked => {
                    p.player_piece = Math.mod(p.player_piece + 1, 3);
                }
            }
        }
        Button {
            text: "start game";
            clicked => {
                root.request_run_game();
            }
        }
    }
}



